# Generated by Django 2.2 on 2019-06-06 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='blog/')),
                ('content', models.TextField(default=None)),
                ('draft', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='singlepageblog.Tag')),
            ],
        ),
    ]
