# Generated by Django 2.2 on 2019-06-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepageblog', '0002_auto_20190616_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
