# Generated by Django 2.2 on 2019-06-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singlepageblog', '0003_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date'], 'verbose_name': 'My Blogs'},
        ),
    ]
